import {
  API_BASE as RUNTIME_API_BASE,
  GOOGLE_ANDROID_CLIENT_ID as RUNTIME_GOOGLE_ANDROID_CLIENT_ID,
  GOOGLE_EXPO_CLIENT_ID as RUNTIME_GOOGLE_EXPO_CLIENT_ID,
  GOOGLE_IOS_CLIENT_ID as RUNTIME_GOOGLE_IOS_CLIENT_ID,
  GOOGLE_WEB_CLIENT_ID as RUNTIME_GOOGLE_WEB_CLIENT_ID,
} from './runtimeEnv.generated';

const FALLBACK_API_BASE = 'https://technical-app-api-production.up.railway.app';
const FALLBACK_GOOGLE_WEB_CLIENT_ID =
  '591242688623-jo1iilo2vgli5e03pjt8a1ceja1o0277.apps.googleusercontent.com';
const FALLBACK_GOOGLE_ANDROID_CLIENT_ID =
  '591242688623-e0k5j6g93itil9641jv4trmqet1v8tq0.apps.googleusercontent.com';
const FALLBACK_GOOGLE_IOS_CLIENT_ID =
  '591242688623-7l33l1a86g8u33f0306jk3dev7dorg5f.apps.googleusercontent.com';

export const API_BASE =
  RUNTIME_API_BASE || process.env.EXPO_PUBLIC_API_BASE || FALLBACK_API_BASE;
export const GOOGLE_WEB_CLIENT_ID =
  RUNTIME_GOOGLE_WEB_CLIENT_ID ||
  process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID ||
  FALLBACK_GOOGLE_WEB_CLIENT_ID;
export const GOOGLE_ANDROID_CLIENT_ID =
  RUNTIME_GOOGLE_ANDROID_CLIENT_ID ||
  process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID ||
  FALLBACK_GOOGLE_ANDROID_CLIENT_ID;
export const GOOGLE_IOS_CLIENT_ID =
  RUNTIME_GOOGLE_IOS_CLIENT_ID ||
  process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID ||
  FALLBACK_GOOGLE_IOS_CLIENT_ID;
export const GOOGLE_EXPO_CLIENT_ID =
  RUNTIME_GOOGLE_EXPO_CLIENT_ID || process.env.EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID || '';
