const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const envPath = path.join(projectRoot, '.env');
const outDir = path.join(projectRoot, 'src', 'config');
const outPath = path.join(outDir, 'runtimeEnv.generated.js');

const ENV_KEYS = [
  'EXPO_PUBLIC_API_BASE',
  'EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID',
  'EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID',
  'EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID',
  'EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID',
];

const parseEnvFile = source => {
  const result = {};

  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const equalIndex = line.indexOf('=');
    if (equalIndex < 0) {
      continue;
    }

    const key = line.slice(0, equalIndex).trim();
    let value = line.slice(equalIndex + 1).trim();

    const quoteMatch = value.match(/^(['"])(.*)\1$/);
    if (quoteMatch) {
      value = quoteMatch[2];
    }

    result[key] = value;
  }

  return result;
};

const envMap = fs.existsSync(envPath)
  ? parseEnvFile(fs.readFileSync(envPath, 'utf8'))
  : {};

const toJS = key => JSON.stringify(envMap[key] || '');

const fileBody = `// Auto-generated by scripts/sync-env.js
// Do not edit manually.
export const API_BASE = ${toJS('EXPO_PUBLIC_API_BASE')};
export const GOOGLE_WEB_CLIENT_ID = ${toJS('EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID')};
export const GOOGLE_ANDROID_CLIENT_ID = ${toJS(
  'EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID',
)};
export const GOOGLE_IOS_CLIENT_ID = ${toJS('EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID')};
export const GOOGLE_EXPO_CLIENT_ID = ${toJS(
  'EXPO_PUBLIC_GOOGLE_EXPO_CLIENT_ID',
)};
`;

fs.mkdirSync(outDir, {recursive: true});
fs.writeFileSync(outPath, fileBody, 'utf8');

const missing = ENV_KEYS.filter(key => !envMap[key]);
if (missing.length > 0) {
  console.log(`[env:sync] Missing keys in .env: ${missing.join(', ')}`);
}

console.log('[env:sync] Updated src/config/runtimeEnv.generated.js');
